version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gympass
      POSTGRES_DB: gimnasio
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    ports:
      - "3001:3001"

volumes:
  db-data:
